### ISSUE TITLE
Partials, caching?

### ISSUE THREAD

**Issue by bradgreens** [simnalamburt/gulp-slm#10]
I have a gulp stack that is roughly the following:
```
var gulp         = require('gulp');
var express      = require('express');
var livereload   = require("gulp-livereload");
var slm          = require("gulp-slm");
var watch        = require('gulp-watch');

gulp.task('express', function() {
  var app = express();
  app.use(express.static(__dirname));
  app.listen(4000);
});

var slmFiles  = [
  "./_pre-assets/slm/partials/*.slm",
  "./_pre-assets/slm/*.slm"
]
var slmOutput = "./dist/html";

gulp.task('slm', function(){
  return gulp.src(slmFiles)
    .pipe(slm())
    .pipe(gulp.dest(slmOutput));
});

gulp.task('watch', function(){
  livereload.listen();
  gulp.watch(slmFiles, ['slm']);

  var watchDirs = [
    './dist/html/*.html'
  ]

  gulp.watch(watchDirs).on('change', livereload.changed);
});

gulp.task('default', ['express', 'watch']);
```

An example HTML snippet of what I'd like to do is the following:
```
html
body
  .main-background
    main.main
      | Boy I'd love to edit this partial and see the updates... but after the first build it "sticks"
      == partial('partials/_header')
```

You can assume the header file is there, no errors and always renders on startup of `gulp`.

I'm having issues with editing the partials, as well as the root templates after `gulp-slm` compiles the first batch of `*.html` files. Specifically edits to the root templates update, but not the partials. This seems to be true even if I edit the partial and save, then edit the root and save. The root updates but not the partial (unless I restart gulp).

I've also tried combining this with tools such as https://github.com/gulpjs/gulp/blob/master/docs/recipes/delete-files-folder.md. Where my idea was to clobber the entire output folder and rebuild it. Sadly this also doesn't work, it seems that either `gulp-slm` or `slm` might be caching the partials, and wiping the output folder isn't relevant.

Hopefully this makes sense... I've been messing with my configurations for a couple hours.

**Comment by simnalamburt** [comment]
Acknowledged, please give me some time to test it (recently I got very busy).

But first, I'm afraid I guess it's very likely due to [`slm`][slm]. Since `gulp-slm` is just wrapper of `slm`, its source code is [dead-simple][src]. It doesn't even create any file, but just creates an stream an passes to gulp.

[slm]: https://github.com/slm-lang/slm
[src]: https://github.com/simnalamburt/gulp-slm/blob/master/src/index.js

**Comment by bradgreens** [comment]
I put some console logs in `src/index.js`. I can tell it's picking up the changes to the partials and firing off the `slm` lib. Enough evidence for me to push this along to the `slm` team. I started a test project to reproduce. https://github.com/bradgreens/github-test-gulp-slm-partials. Do as you wish with this Issue report.

**Comment by bradgreens** [comment]
Moved to: https://github.com/slm-lang/slm/issues/5
